name: Publish to WinGet
on:
  release:
    types: [released]
jobs:
  publish:
    runs-on: windows-latest # action can only be run on windows
    steps:
      - uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: CoolPlayLin.LANDrop
          version: ${{ github.event.release.tag_name }}
          token: ${{ secrets.WINGET_TOKEN }}